### ISSUE TITLE
dynamically retrieve secret contract address

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#13]
Question from @nionis -- https://github.com/nionis/enigma-benchmarking/issues/2

He wants to understand:

> if there is a place where we can find the secret contract address other than the one within tests.
> Currently it feels a bit hacky but acceptable I suppose for mainnet since the address doesn't change.

**Comment by lacabra** [comment]
His rationale is correct. We currently write it to disk on a text file that is easily readable and parseable. On mainnet, these addresses will be hardcoded once a given contract is deployed, so I am marking this a will not implement.

@ainsleys you can close this if you find this satisfactory.

**Comment by ainsleys** [comment]
Closing this, thanks for the explanation @lacabra
