### ISSUE TITLE
problem with decryptTaskResult, only appearing in react app

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#17]
Here's the link -- 
this is one of our bounty devs, and he's run into quite a lot of trouble. It will be great if we can help get this resolved. 

https://forum.enigma.co/t/problem-with-decrypttaskresult-only-in-react-app/1106

**Comment by lauracw100** [comment]
I'll check it out and see if I can help him.

**Comment by lacabra** [comment]
Hold on @lauraweindorf 🙃, coincidentally this is being tracked in here already: enigmampc/enigma-contract#154

**Comment by lauracw100** [comment]
oh ok cool!

**Comment by guix77** [comment]
Problem solved for me. I forgot to `getTaskResult` before `decryptTaskResult`... https://github.com/guix77/enigma-secret-access-control/commit/1f1e0019a608626a272f71e6ffb6370f649a00bc
