### ISSUE TITLE
unable to test signature verification because of errors

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#2]
Peter (working on Rock paper scissors bounty) is blocked by the following errors 

"Wrong epoch for this task” was thrown, throw an Error 
Incorrect nonce yielding bad secret contract address
“Allowance not enough” was thrown, throw an Error 

He isn't able to test out how to verify signatures because he's held up on these issues that are seemingly related to the testnet.

**Comment by ainsleys** [comment]
OK, thanks @lacabra . I'll close this and open one for each one of them.

**Comment by lacabra** [comment]
Thank you
