### ISSUE TITLE
Can a TEE "ring of trust" be wrapped around any layer of the Enigma Protocol?

### ISSUE THREAD

**Issue by lauracw100** [enigmampc/dev-help#23]
https://forum.enigma.co/t/t-e-e-ring-of-trust-with-forcibly-distributed-token/1117

Econymous is asking: 

> If Enigma could make use of this contract model, there would have to be some type of “migration” function implemented. A transition. or potentially using Enigma to define a cluster of contracts associated with each other.
> Unless there is some value that foam has in the centralized world.
> 
> The contract I created forcibly distributes the “resolve token” supply.
> This distribution can be used to create a ring of trust, such as what’s needed for proof of stake sidechains.
> I believe this ring of trust can be applied to devices associated with FOAM’s protocol. Bringing finality closer to the beacon event layer.
> 
> That is all. **Just let me know if a “ring of trust” can be wrapped around any layer of your protocol.
> I spoke to another member here a while ago about a research grant related to this idea.**

cc: @ainsleys @lacabra

**Comment by ainsleys** [comment]
responded asking for clarification on "ring of trust"

**Comment by ainsleys** [comment]
I'm going to close this because I think it's more of a brainstormng discussion rather than soemthing that requires support at this time.
