### ISSUE TITLE
“discovery init” error

### ISSUE THREAD

**Issue by levackt** [enigmampc/dev-help#26]
[forum question](https://forum.enigma.co/t/error-running-discovery-init/1122)

> The following error message shows up when I run “discovery init”.
my environment:
ubuntu 16.04
node -v : 10.17.0 (system install without using nvm)
npm -v : 6.11.3
discovery -v: 0.1.3

> added 452 packages from 338 contributors and audited 62580 packages in 25.479s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
? Running in SGX Hardware (HW) or Software (SW) mode? (HW/sw) sw
? About to pull Docker images. This requires 15 GB of space. Continue? (Y/n)
Pulling Enigma Docker images...
(node:15396) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'row' of undefined
    at Object.module.exports.pullImage (/usr/lib/node_modules/@enigmampc/discovery-cli/src/docker.js:64:33)
    at /usr/lib/node_modules/@enigmampc/discovery-cli/src/index.js:183:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by levackt** [comment]
Seems they haven't selected Y to pull images and the cli timed out, will try reproduce before I respond.

**Comment by lacabra** [comment]
It is strange though, because I don't think there is a timeout there. It should wait "forever" for user input. My guess is that they pressed "Enter" which accepts the "Y" as the default value. So then the error is indeed with the pulling of docker images, but that is also strange if it works for the rest of us...

**Comment by levackt** [comment]
Yep, I'm still waiting for a timeout, which as you say probably won't happen.

**Comment by lacabra** [comment]
alternatively, hit "enter" and you'll see how no answer gets recorded, and the process continues :)

**Comment by levackt** [comment]
That's what I usually do so don't expect any surprise this time. 
Will give it some more time anyway, just so I don't have doubts about it later, meanwhile I'm looking at how the [cursor position](https://github.com/enigmampc/discovery-cli/blob/master/src/docker.js#L64) works for the next clue.

**Comment by levackt** [comment]
In a different terminal I confirmed it won't print anything if I choose defaults, so that was indeed a straw :)

**Comment by levackt** [comment]
Will also try their node version

**Comment by levackt** [comment]
node 10.17 worked for me, on MacOS

I found similar [issues with get-cursor-position](https://github.com/bubkoo/ascii-progress/issues/14) and it was their OS, Redhat 7.4 and Raspbian

**Comment by lacabra** [comment]
ah, yes, this is related to the progress bar that displays how the downloads progress. Thanks for digging this. Not sure there is anything we can do at the moment. My suggestion is as follows:

Get back to the user and say that the installation was successful and that he has to manually pull the docker images with `docker-compose pull`. Once that completes, the installation will be completed, as if it had succeeded the first time.

**Comment by levackt** [comment]
Confirmed resolved
