### ISSUE TITLE
Input size limits of tasks and secret contracts

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#3]
Is the input size of a task or a contract limited to 1MB? 
is it possible to include an external crate with more than 1MB?

https://forum.enigma.co/t/data-input-size-limit-increase-1mb/1092

**Comment by lauraweindorf** [comment]
Secret contract inputs are limited to 1MB. That may be optimized after Mainnet. 
Secret contracts themselves are also limited to 1MB, including any imported Rust crates.

**Comment by lauracw100** [comment]
@sepia is asking about using an extern crate that's about 200kb but has dependencies, some of which are enigma-core, that are around 2MB:

Is it possible to use enigma-core dependencies inside the secret contract?

I've suggested trying it with the extern crate and see if the compiled .wasm is <= 1MB.

**Comment by lauracw100** [comment]
This article is a good resource for optimizing a `.wasm` build: 

> how to optimize your .wasm build for a small code size footprint, and how to identify opportunities to change your Rust source such that less .wasm code is emitted

https://rustwasm.github.io/docs/book/reference/code-size.html

**Comment by lauracw100** [comment]
Requested more info including his `Cargo.toml` and secret contract code.

**Comment by ainsleys** [comment]
@lauraweindorf thanks for helping on this one! I'm going to close it, if user responds with new problems let's open a new issue. I think we addressed the main question here.
