### ISSUE TITLE
Dev following millionaire's tutorial is getting error that task key pair needs to be set

### ISSUE THREAD

**Issue by lauracw100** [enigmampc/dev-help#32]
From the forum:
https://forum.enigma.co/t/error-when-running-discovery-test-for-tutorial-millionaires-problem/1130

Dev is following the blog post [Getting Started with Enigma: An Intro to Secret Contracts](https://blog.enigma.co/getting-started-with-enigma-an-intro-to-secret-contracts-cdba4fe501c2).

The error is `Error: Need to set task key pair first`.

I told him to add the `enigma.setTaskKeyPair('cupcake')` call to the test JS.

The tutorial code for `test/test_millionaires_problem.js` in the blog post needs to be updated to include setting the task key pair.

cc @ainsleys @lacabra

**Comment by levackt** [comment]
In his latest error I see he's trying to connect to localhost:3346, and this is no longer exposed, he should use the nginx port 3333

**Comment by levackt** [comment]
> In his latest error I see he's trying to connect to localhost:3346, and this is no longer exposed, he should use the nginx port 3333

@ainsleys @lacabra Besides the [getting started guide](https://blog.enigma.co/getting-started-with-enigma-an-intro-to-secret-contracts-cdba4fe501c2) needing an  update since [commit](https://github.com/enigmampc/discovery-cli/commit/72b8c2d02f3e990a3cf8f047dc0c6a3412dfc157) , we also need to update the [README which mentions 3346](https://github.com/enigmampc/discovery-cli/blame/master/README.md#L86) 
Not sure what else so putting it out here in the meantime.

**Comment by ainsleys** [comment]
Is this the same user on discord (Santiago)?

**Comment by lauracw100** [comment]
Oh no, this user is KanaGold.

**Comment by lauracw100** [comment]
Trying to make sure all instances documented here. From @Santiago:

`the port is also wrong within the client/src/utils/getEnigmaInit.js in the boilerplate code created during init`

as @levackt mentioned above it should be `3333`.

That code also needs to have the `enigma.setTaskKeyPair('cupcake');` call.

cc @lacabra @ainsleys

**Comment by ainsleys** [comment]
Hmm it seems a few different users are experiencing similar issues, someone at the hackathon is also having this. Maybe @lacabra can help

**Comment by levackt** [comment]
They get stuck on the port or the task key pair? 

It may be a bit late now and of course we have to update the guide to setTaskKeyPair anyway, but the docker-compose.yml should perhaps have kept the old port 3346:3346 mapping in p2p, which would then still work with the guide. I just tested that to be sure and it works.
But the horse has left the barn :)

**Comment by levackt** [comment]
> > In his latest error I see he's trying to connect to localhost:3346, and this is no longer exposed, he should use the nginx port 3333
> 
> @ainsleys @lacabra Besides the [getting started guide](https://blog.enigma.co/getting-started-with-enigma-an-intro-to-secret-contracts-cdba4fe501c2) needing an update since [commit](https://github.com/enigmampc/discovery-cli/commit/72b8c2d02f3e990a3cf8f047dc0c6a3412dfc157) , we also need to update the [README which mentions 3346](https://github.com/enigmampc/discovery-cli/blame/master/README.md#L86)
> Not sure what else so putting it out here in the meantime.

Kicked off a [PR](https://github.com/enigmampc/discovery-cli/pull/24) for the port number

**Comment by lacabra** [comment]
I have merged @levackt commit enigmampc/discovery-cli#24
and I have updated the code displayed on [Part 2 of the getting started guide](https://blog.enigma.co/getting-started-with-enigma-an-intro-to-secret-contracts-cdba4fe501c2) (both the port change and `setTaskKeyPair`)

Let me know if additional changes are needed anywhere else. Thanks!

**Comment by lauracw100** [comment]
That's look good @lacabra. There just one more place, under the `client/src/utils` directory:

`getEnigmaInit.js`

Needs the port change and the `setTaskKeyPair`.

That code comes from the template dapp repo I think ...

Thanks for updating these!

**Comment by lacabra** [comment]
@lauraweindorf can you point to me what repo are you referring to? Thanks!

**Comment by lauracw100** [comment]
I believe it's this one that is used to create the client stuff when doing `discovery init`:

_discovery-template-dapp_

https://github.com/enigmampc/discovery-template-dapp/blob/master/src/utils/getEnigmaInit.js

**Comment by levackt** [comment]
For the port in the template there's an [approved PR ](https://github.com/enigmampc/discovery-template-dapp/pull/1) in the pipeline, 

If I understand correctly the taskkeypair isnt needed by the client unless its also deploying the contract on the fly, which the template doesn't do of course.

**Comment by lauracw100** [comment]
Oh, I didn't realize that. Good catch!

**Comment by lauracw100** [comment]
Closing this because it's not an issue any longer, since the most recent updates to `discovery-cli 0.1.8`.
