### ISSUE TITLE
Any way to privately obtain blockchain data from within a secret contract?

### ISSUE THREAD

**Issue by levackt** [enigmampc/dev-help#33]
[forum post](https://forum.enigma.co/t/any-way-to-privately-obtain-blockchain-data-from-within-a-secret-contract/1136)

> i.e. call a function in a secret contract that does an ethereum address balance query, without the host running the TEE being able to monitor what address was queried.

> Bonus if the response can be signed with an enclave’s embedded private key.

> Answer from discord: (@ainsleys )
> 'We don’t currently natively support TLS connections right now, but there are a few options to work around. Currently you could use a trusted oracle of some kind to submit the required data as a > Task, and have the secret contract return that data so that it can be verified as correct by the smart contract upon completion.

> This is a good question for the forum-- if you raise it there, we can give a more in-depth discussion.’

**Comment by ainsleys** [comment]
This commenter will be at Eth waterloo, I think!

**Comment by ainsleys** [comment]
Closing this, as the answer is no, you can't do this (for the time being) and we're aware of the product need and tracking it elsewhere.
