### ISSUE TITLE
Recommended error handling pattern for secret contracts?

### ISSUE THREAD

**Issue by levackt** [enigmampc/dev-help#49]
[forum post](https://forum.enigma.co/t/recommended-error-handling-pattern-for-secret-contracts/1208)

> Hi. I am writing some smart contract code in Rust, but I have a question about error handling. The usual pattern for error handling in Rust uses Result and Error. But I see in secret contract code their use produces the error

> the trait `eng_wasm::eng_pwasm_abi::eth::AbiType` is not implemented for `core::result::Result<(), Error>`
> So how should potential errors and known failure conditions be handled in Enigma secret contracts?

**Comment by cankisagun** [comment]
I believe this was something raised in ETHWaterloo as well @ainsleys ?

**Comment by ainsleys** [comment]
I don't recall @cankisagun -- I think the team working on ML requested more descriptive error messages for when contracts compile but still won't run

**Comment by levackt** [comment]
Result is part of std, so excluded by no_std and won't work.
I suggested Brendan "panics" with some examples from the docs and Salad.
