### ISSUE TITLE
User unable to compile test contract

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#5]
https://forum.enigma.co/t/app-js-and-syntax-error/1090/2

**Comment by ainsleys** [comment]
Adding @levackt who is helping this user in the forum

**Comment by lacabra** [comment]
There seems to be a typo in one of the user's files.
Proposed change, waiting to hear confirmation from the user that that solves the problem.

**Comment by levackt** [comment]
I don't think there was a problem with Enigma but the user got stuck in the deprecated repo, tried to encourage using discovery.
We can probably close this one now.
