### ISSUE TITLE
Compute task status 3 during “discovery test”

### ISSUE THREAD

**Issue by levackt** [enigmampc/dev-help#57]
[forum post](https://forum.enigma.co/t/compute-task-status-3-during-discovery-test/1262)

> I am working on a project that’s very similar to enigma-secret-access-control 1 and get the following output after running “discovery test”.
> SNIP
> What am I doing wrong? I’ve been dealing with this for the past day and have been trial-n-erroring it by altering the secret contract’s reveal_expired_secrets function and the test script and have had no luck.

I've noticed and mentioned this from the error logs
> core_1 | Error in execution of smart contract function: Error in execution of WASM code: unreachable

While logs and snippets are included, I've asked realjohnward for a github project, else I'll piece it together and try to get it going in the coming days.

**Comment by levackt** [comment]
Narrowed the issue down to using chrono to get the timestamp, looks like chrono should support it and I shared the github issue with possible solutions.

Basically he's storing timestamps of secrets and the owner can later read them once they're expired.

**Comment by levackt** [comment]
>I appreciate your reply @taariq

>Over the past week I’ve been looking at the links you provided and they seem to all lead to dead ends, as I’ve tried implementing every solution. After a week of googling I haven’t found one single “no_std”-compatible crate w/ a function that outputs timestamps without the need for input.

>I believe the value of Enigma would increase tremendously if timestamps could be produced inside of enclaves, as it would allow for “smart-private” computation.

> Do you think it would be possible to have a “now()” preprocessor? It would work in a similar nature to the “rand()” preprocessor in that it would require no input parameters.

WDYT? @ainsleys  @reuvenpo 

Maybe in the meantime there's a workaround or new approach to his problem.

**Comment by reuvenpo** [comment]
Despite the fact we do not use their SDK, fortanix puts this quite succinctly in their documentation:
>Timekeeping in secure enclaves is an unsolved problem.
https://edp.fortanix.com/docs/concepts/rust-std/#codestdtimecode

(Fortanix provides an SGX enclave SDK in rust which is analogous to the one we're using. The linked page explains various limitations that implementations of standard libraries face when trying to work from within enclaves, and apply to the functions available to developers of secret contracts.)

Our enclaves use the standard library implemented by the Baidu team, documented here:
https://github.com/apache/incubator-teaclave-sgx-sdk
But the secret contracts themselves are running inside a WASM runtime running _inside_ the enclave runtime, and thus are subject to even more limitations. They are compiled to target rust's `wasm32-unknown-unknown` target, and use the standard library that it provides. As the target name suggests, it does not (and in our case _can not_) assume it has any OS interfaces available to it, and thus panics or aborts when it sees an attempt to use them (as this user observed). All the I/O services that are available to secret contracts (secret state, randomness, etc) are exposed through custom functions available in the `eng_wasm` crate. We could add a method which tries to fetch the time from the environment and return it into the WASM runtime, but we will not have a real way of implementing it in a trusted way. (at least not that i can think of)

CC: @moriaab @AvishaiW

**Comment by reuvenpo** [comment]
The user can perhaps initialize their contract with the public key of a trusted "time service", and expose a secret contract method that accepts a timestamp (encoded in some format) and a signature of that timestamp made by the trusted service. This timestamp can be stored in secret storage, and the service could periodically let the smart contract know what time it is. The contract can then assume any other function is invoked within an interval after the "last reported time".

**Comment by levackt** [comment]
Thanks for the detailed info @reuvenpo , sharing it verbatim.

**Comment by levackt** [comment]
Closed with kind thanks to @reuvenpo
