### ISSUE TITLE
what are the differences between using pub interface public functions in contract implementation

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#6]
Question in forum: 

Summary:
What are the differences between using public_interface trait, then implement that trait for the public functions which will interact with UI part vs implement directly public functions right in contract implementation (not using pub_interface)?

Secondly, if I use pub_interface trait, implement it later, is there a way to point to &mut self if I call private functions in the public functions?

https://forum.enigma.co/t/what-are-the-differences-between-using-pub-interface-public-functions-in-contract-implementation/1076

**Comment by lauraweindorf** [comment]
1. _pub_interface_ is an Enigma attribute macro, part of the _eng_wasm_derive_ crate, that decorates the _ContractInterface_ trait and enables the definition and invocation of your secret contract. Without it your contract cannot be used via EnigmaJS calls.

2. The Enigma secret contracts don’t use the Rust std library which implements the implicit passing of the self reference to methods. To have your called functions work with _self_ you have to manually pass a reference to the object or instance it needs.

More details and examples here:
https://forum.enigma.co/t/what-are-the-differences-between-using-pub-interface-public-functions-in-contract-implementation/1076
