### ISSUE TITLE
Where are the enigmacli docs?

### ISSUE THREAD

**Issue by lauracw100** [enigmampc/dev-help#66]
It would be nice to have docs on all the enigmacli commands, added to the EngimaBlockchain repo.

I'm assuming it's the pretty much the same as what's here: https://github.com/cosmos/gaia/blob/master/docs/resources/gaiacli.md

cc @assafmo @levackt @ainsleys

**Comment by lauracw100** [comment]
If the enigmacli is basically a clone of the gaiacli, I can do a PR with the enigmacli version of that?

**Comment by ainsleys** [comment]
I think it's similar enough that you can do that @lauraweindorf and if we need to remove or modify any of the commands we can make those changes. I'd suggest going ahead and doing that but with a disclaimer at the top that it's WIP until we can confirm.

**Comment by lauracw100** [comment]
Okay sounds good. Thanks, Ainsley!

**Comment by assafmo** [comment]
Thanks @lauraweindorf, we already ported some of it to our repo (The gov section).
I think what's missing from the above link is the `unjail` command and the `gaiacli q txs` & `gaiacli q tx` commands.

**Comment by lauracw100** [comment]
Got it, thanks @assafmo!

**Comment by lauracw100** [comment]
PR submitted

I believe I got everything 😄. Closing this issue ... but we can re-open if necessary.

cc @assafmo @ainsleys

**Comment by assafmo** [comment]
Thanks @lauraweindorf, merged. :tada:
