### ISSUE TITLE
Incorrect nonce yielding bad secret contract address

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#9]
This error is reported by Peter, who was working on rock paper scissors bounty.

**Comment by ainsleys** [comment]
Peter provided error logs for this one here: https://forum.enigma.co/t/two-errors-not-enough-allowance-and-incorrect-nonce/1093

**Comment by lauraweindorf** [comment]
Related to https://github.com/enigmampc/dev-help/issues/10.

**Comment by lauracw100** [comment]
I was able to reproduce the errors, both of which showed the following error during the `enclave` execution of the task:

`core_1      | Error in execution of smart contract function: Input Error: Cryptography Error: DecryptionError`

The secret contract had a statement initializing an array (a typo) that seems to be culprit:
`let mut new_sig: [u8; 65] = [0u8; 65];`

Changing the statement to initialize with `[0; 65]` resolved the errors for me.

Waiting to hear from Peter if it fixes the issue for him too.

**Comment by lauracw100** [comment]
Fixing the initialization of his `new_sig` array resolved the errors. Peter mentioned that he got that code from the `erc20` example SC code at: https://github.com/enigmampc/enigma-core/blob/develop/examples/eng_wasm_contracts/erc20/src/lib.rs.

Opened issue: https://github.com/enigmampc/enigma-core/issues/228
